esphome:
  name: esp32-test
  includes:
    - LD1125H.h
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
  level: DEBUG
  baud_rate: 0
api:
ota:
  password: "1c2b59f17342fcc0bfc95c597a85efc8"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
uart:
  id: LD1125H_UART_BUS
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200
  stop_bits: 1
  #setup_priority: -100
light:
  - platform: status_led
    name: "ESP32-TEST LED"
    pin: GPIO2
web_server:
  port: 80
sensor:
  - platform: wifi_signal
    name: "ESP32-TEST WiFi Signal Sensor"
    update_interval: 60s
  - platform: custom
    lambda:
      auto LD1125H_sensor = new LD1125H(id(LD1125H_UART_BUS));
      App.register_component(LD1125H_sensor);
      return {LD1125H_sensor->distance_sensor};
    sensors:
    - name: "LD1125H Distances"
      unit_of_measurement: "m"
      accuracy_decimals: 2
      id: ld1125h_distance
      filters:
      - sliding_window_moving_average:
          window_size: 50
          send_every: 3
text_sensor:
  - platform: custom
    lambda:
      auto LD1125H_sensor = new LD1125H(id(LD1125H_UART_BUS));
      App.register_component(LD1125H_sensor);
      return {LD1125H_sensor->status_sensor, LD1125H_sensor->uart_text};
    text_sensors:
    - name: "LD1125H Occupancy"
      id: ld1125h_status
    - name: "UART_readline"
      id: uart_readline
      internal: False
